spring.datasource.url=jdbc:postgresql://localhost:5432/web
spring.datasource.driver=com.postgresql.cj.jdbc.Driver
spring.datasource.username=postgres
spring.datasource.password=8589415
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
debug=true
spring.thymeleaf.cache=false
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.port=8080
security.basic.enables=false

